apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: {{ .Values.metadata.name}}
  namespace: {{.Values.metadata.namespace}}
spec:
  license:
    accept: {{ .Values.spec.license.accept}}
    license: {{ .Values.spec.license.license}}
    metric: {{ .Values.spec.license.metric}}
    use: {{ .Values.spec.license.use}}
  queueManager:
    mqsc:
      - configMap:
          items:
            - static-definitions.mqsc
          name: mqsc-configmap
    name: QM2
    image: >-
      docker.io/ibmcom/mq@sha256:ab781c17c563c216002f3abb737aebcbe1e586d0b8c1dab1a2da8294e6edcc2c
    metrics:
      enabled: {{ .Values.spec.queueManager.metrics.enabled}}
      resources:
      limits:
        cpu: {{ .Values.spec.queueManager.resources.limits.cpu}}
        memory: {{ .Values.spec.queueManager.resources.limits.memory}}
      requests:
        cpu: {{ .Values.spec.queueManager.resources.requests.cpu}}
        memory: {{ .Values.spec.queueManager.resources.requests.memory}}
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: {{ .Values.spec.queueManager.route.enabled}}
    name: {{ .Values.spec.queueManager.name}}
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: {{ .Values.spec.queueManager.imagePullPolicy}}
    debug: false
    logFormat: Basic
    availability:
      type: SingleInstance
      updateStrategy: RollingUpdate
    storage:
      defaultClass: {{ .Values.spec.queueManager.storage.defaultClass}}
      persistedData:
        enabled: false
      queueManager:
        type: {{ .Values.spec.queueManager.storage.queueManager.type}}
        class: {{ .Values.spec.queueManager.storage.defaultClass}}
        size: 2Gi
      recoveryLogs:
        enabled: false
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
        - env:
            - name: QMSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  version: {{ .Values.spec.version}}
  web:
    enabled: {{ .Values.spec.web.enabled}}