# Default values for ibm-dpservice-instance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  namespace: datapower
spec:
  license: L-RJON-CCCP46
  use: nonproduction
  serviceAccount: sa-datapower
  imagePullSecrets: ibm-entitlement-key
  users:
    passwordSecret: admin-credentials
  imagePullPolicy: IfNotPresent
  version: 10.0-cd
  podManagementPolicy: Parallel
  storage:
    class: managed-nfs-storage
    path: dp-service
    size: 100Mi
    type: persistent
    volumeMode: Filesystem
  replicas: 1
  resources:
    memory: 4Gi
    requests:
      cpu: '1'
  readinessProbe:
    failureThreshold: 3
    port: 7879
  users:
    accessLevel: privileged
    name: admin
    passwordSecret: datapower-user
  domains:
    certs:
      certType: sharedcerts
      secret: datapower-cert
    name: default
  imagePullPolicy: IfNotPresent
  version: 10.0-cd
  podManagementPolicy: Parallel
  replicas: 1
  labels:
    app: dpgui-deployment
